artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_link: "adityajn105/flickr8k"
  local_data_file: artifacts/data_ingestion/data

tokenization:
  root_dir: artifacts/tokenization
  token_file: artifacts/tokenization/data
  caption_file: artifacts/data_ingestion/data/captions.txt
  tokenizer_type: "basic_english"
  unk_token: "<unk>"
  pad_token: "<pad>"
  sos_token: "<sos>"
  eos_token: "<eos>"


custom_dataset:
  root_dir: artifacts/custom_dataset
  image_dir: artifacts/data_ingestion/data/Images
  caption_file: artifacts/data_ingestion/data/captions.txt
  vocab: artifacts/tokenization/data
  save_file_path: artifacts/custom_dataset/data

model_trainer:
  root_dir: artifacts/model_trainer
  data_dir: artifacts/custom_dataset/data
  token_dir: artifacts/tokenization/data